name: ml-sentinel2
channels:
  - pytorch
  - fastai
  - conda-forge
dependencies:
  - jupyter=1.0.*
  - matplotlib=3.1.*
  - numpy=1.17.*
  - pip=19.3.*
  - python=3.7.*
  - rasterio=1.1.*
  - fastai=1.0.*
  - pip:
    - opencv-python==4.1.*
